name: workflow_secrets
on:
    workflow_dispatch

env:
    DB_P:${{secrets.DB_PASSWORD}}

jobs:
    test-secrets:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: check env p
              run: echo "p=${{ env.DB_P }}"
